sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t llewellynthomas/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true llewellynthomas/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-589463386051"
  bucket_path: "docker-react"
  on:
    branch: master

access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY
